### ISSUE TITLE
Cannot access Vault UI using IP address

### ISSUE THREAD

**Issue by jasonwhitedev** [scriptcamp/kubernetes-vault#1]
In the post https://devopscube.com/vault-in-kubernetes/

it refers to IP address: http://33.143.55.228:32000 for the UI. 

Where does this IP come from. Is there an Ingress step that I am missing?

Currently using port-forwarding to access the UI.

**Comment by scriptcamp** [comment]
its the node IP address as the service is exposed as NodePort
